class IPCDevice:
    def __init__(self, pointer: int) -> None: ...
    def getModel(self) -> str: ...
    def getVideoPort(self) -> int: ...
    def handle(self) -> int: ...
    def supportMotor(self, listType: int, channelID: int) -> bool: ...
