from tplink.sdk.TPPlayer import TPPlayer
from tplink.sdk.TPSDKContext import TPSDKContext

class TPOpenSDK:
    def __init__(self) -> None: ...
    def createPlayer(self) -> TPPlayer: ...
    def destorySDKContext(self) -> None: ...
    def getSDKContext(self) -> TPSDKContext: ...
    @staticmethod
    def getInstance() -> TPOpenSDK: ...
