from typing import Any, Callable

from tplink.sdk.IPCDevice import IPCDevice

PlayerChangeQualityHandler = Callable[[int], None]
PlayerPlayPausedHandler = Callable[[], None]
PlayerPlayStartHandler = Callable[[], None]
PlayerPlayStopHandler = Callable[[int], None]
PlayerPlayTimeHandler = Callable[[int], None]
PlayerReceiveDataHandler = Callable[[Any, int], None]
PlayerRecordDurationHandler = Callable[[int], None]
PlayerRecordStartHandler = Callable[[], None]
PlayerRecordStopHandler = Callable[[int, Any], None]
PlayerSnapshotHandler = Callable[[int, Any], None]

class TPPlayer:
    def __init__(self) -> None: ...
    def changeQuality(self, quality: int) -> int: ...
    def pause(self) -> int: ...
    def release(self) -> None: ...
    def resume(self) -> int: ...
    def seek(self, offsetTime: int) -> int: ...
    def setOnChangeQualityHandler(self, handler: PlayerChangeQualityHandler) -> None: ...
    def setOnPlayPausedHandler(self, handler: PlayerPlayPausedHandler) -> None: ...
    def setOnPlayStartHandler(self, handler: PlayerPlayStartHandler) -> None: ...
    def setOnPlayStopHandler(self, handler: PlayerPlayStopHandler) -> None: ...
    def setOnPlayTimeHandler(self, handler: PlayerPlayTimeHandler) -> None: ...
    def setOnReceiveDataHandler(self, handler: PlayerReceiveDataHandler) -> None: ...
    def setOnRecordDurationHandler(self, handler: PlayerRecordDurationHandler) -> None: ...
    def setOnRecordStartHandler(self, handler: PlayerRecordStartHandler) -> None: ...
    def setOnRecordStopHandler(self, handler: PlayerRecordStopHandler) -> None: ...
    def setOnSnapshotHandler(self, handler: PlayerSnapshotHandler) -> None: ...
    def setViewHolder(self, holder: int) -> TPPlayer: ...
    def snapshot(self, uri: str) -> int: ...
    def startPlayback(
        self,
        device: IPCDevice,
        clientId: int,
        channelId: int,
        eventType: int,
        startTime: int,
        endTime: int,
    ) -> int: ...
    def startRealPlay(self, device: IPCDevice, channelId: int = -1, quality: int = 0) -> int: ...
    def startRecord(self, uri: str) -> int: ...
    def stop(self) -> int: ...
    def stopPlayBack(self) -> int: ...
    def stopRecord(self) -> int: ...
