from typing import Optional

from tplink.sdk.IPCDeviceContext import IPCDeviceContext
from tplink.sdk.TPOpenNative import SDKReqCallback

class TPSDKContext:
    def __init__(self) -> None: ...
    def appReqStart(self, bSync: bool = True, callback: Optional[SDKReqCallback] = None) -> int: ...
    def appReqStop(self, bSync: bool = True, callback: Optional[SDKReqCallback] = None) -> int: ...
    def destroyDevCtx(self) -> None: ...
    def getDevCtx(self) -> IPCDeviceContext: ...
